### ISSUE TITLE
Update to 2023.2.28

### ISSUE THREAD

**Issue by HarryGames102** [Devs-Us/Cursed-Among-Us#5]

**Comment by KyleSmith0905** [comment]
Umm, if you want you can learn Among Us modding and update the mod. Though I guess it would be easier if we did it... I am not really into Among Us modding anymore, sorry.

**Comment by HarryGames102** [comment]
What can i do to update it ? 
im courious

**Comment by MrWeasel1000** [comment]
> What can i do to update it ? 
> 
> im courious

I think join the Discord server, make the update, and send it via a ticket. Or send the code changes via the GitHubs🤷‍♂️

**Comment by KyleSmith0905** [comment]
If you're asking how to update because you don't know Among Us modding, than I cannot help you because I forgot how to do it. 😢

**Comment by HarryGames102** [comment]
Its fine i can always learn on youtube

**Comment by KyleSmith0905** [comment]
ok
